<UserControl x:Class="Ru.Rubinst.Document.Main.WPF.Helper.Exceptions.ExceptionView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:system="clr-namespace:System;assembly=mscorlib"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300" d:DataContext="{d:DesignData exceptions:ExceptionModel}">
    <Border>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"></RowDefinition>
                <RowDefinition></RowDefinition>
            </Grid.RowDefinitions>
            <Label FontWeight="Bold" Content="Обработано исключение:"></Label>
            <ScrollViewer Grid.Row="1" VerticalScrollBarVisibility="Auto">
                <ContentControl Content="{Binding Path=Exception}">
                    <ContentControl.Resources>
                        <DataTemplate DataType="{x:Type system:Exception}">
                            <StackPanel>
                                <TextBlock Text="{Binding Path=Message}" TextWrapping="Wrap"></TextBlock>
                                <ContentControl Margin="10 0 0 0" Content="{Binding Path=InnerException}"></ContentControl>
                            </StackPanel>
                        </DataTemplate>
                    </ContentControl.Resources>
                </ContentControl>
            </ScrollViewer>
        </Grid>
    </Border>
</UserControl>
